# Generated by Django 2.0.5 on 2018-05-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_userinfo_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userinfo',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='collect',
            field=models.CharField(default='', max_length=10000, verbose_name='我的收藏'),
        ),
    ]
