# Generated by Django 2.0.5 on 2018-05-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180519_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.CharField(default='', max_length=128, verbose_name='用户名'),
        ),
    ]
