# Generated by Django 2.0.5 on 2018-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180519_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='描述'),
        ),
    ]
