# Generated by Django 2.0.5 on 2018-06-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_goods_publishername'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='accepter',
            field=models.IntegerField(default=0, verbose_name='接收人id'),
        ),
        migrations.AddField(
            model_name='goods',
            name='acceptername',
            field=models.CharField(default='', max_length=128, verbose_name='接收人姓名'),
        ),
        migrations.AddField(
            model_name='goods',
            name='remark',
            field=models.CharField(default='', max_length=128, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='type',
            field=models.IntegerField(choices=[(1, '食物'), (2, '日用品'), (3, '学习用品'), (4, '电子产品'), (5, '体育器材'), (6, '其他')], verbose_name='物品类型'),
        ),
    ]
